language: c
compiler:
  - gcc

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo apt-get install linux-headers-`uname -r`
  - git submodule update --init --recursive

addons:
  coverity_scan:
    project:
      name: "openndr/ndrte"
      description: "NDR Runtime Environment"
    notification_email: seohho@gmail.com
    build_command: "make"
    branch_pattern: master

script:
  - make; ./native/bin/selftest